### ISSUE TITLE
Logger class

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRft#11]
We need some class that will take care of logging & will be platform independent. I was thinking about either class with static log methods or a singleton.
Either way we need #defines to simplify calls to logger to 'LOG_ERROR(_just like printf_);' (same with LOG_INFO and LOG_WARNING).
It needs to log to stdout and to file. Windows version should log to OutputDebugString as well.
- [x] Logger skeleton
- [x] Different log types
  - [x] Log error
  - [x] Log info
  - [x] Log warning
- [x] Defines
- [x] Different platform versions
  - [x] Windows
  - [x] Linux
- [x] Substitute all `// TODO log` comments with `LOG_x` macros

**Comment by mkulagowski** [comment]
There was idea with coloring std output, but imho it's too much hussle in this project.
Logs probably will be used just by devz only and we should manage with unicolor ones ;)

**Comment by mkulagowski** [comment]
My idea:
- Singleton class
- Some log enum class LogType (to hold Info, Error, Warning, Other)
- Log method
- some macros to make calling easier

There are some issues though:
- What arguments should the Log method take? (surely LogType and some message string, sth more?)
- Should Log method use varargs?
- Should `__FILE__` and/or `__LINE__` be used in Log method?

**Comment by lookeypl** [comment]
- Depends on what you wnat to achieve. Looking below, I would probably say "all needed for the schema below".
- I think we can use STL streams to be compliant with C++ standards. It is much slower than varargs, but on this project it will be an achievement for us, to be so new-fashioned. ;)
- Yes, definitely. In logs, file and line are important information. My small suggestion of the format:

```
<timestamp> [<type>] <file> <func>@<line>: <msg>
```

**Comment by lookeypl** [comment]
And of course, most important feature - coloring on console output! Errors should be red, Info should blue, Warnings should yellow, etc.

**Comment by mkulagowski** [comment]
Link to the logger [commit](https://review.gerrithub.io/#/c/254632)

**Comment by mkulagowski** [comment]
Last commits: [1](https://review.gerrithub.io/#/c/254710/) and [2](https://review.gerrithub.io/#/c/256040/).

Merged.
