### ISSUE TITLE
FPS measurement

### ISSUE THREAD

**Issue by lookeypl** [mkulagowski/MineZPRft#15]
We need a way to measure FPS in our game. The problem is, we don't have (and probably won't have) any form of text rendering inside the game.

Our second best option would be printing the FPS value to console from current Timer object mFrameTimer (created as a part of GameManager), however this will flood our logs.

As a solution to this problem, create an AverageCounter class, which will measure an average FPS value and return it for printing inside GameManager.

Features:
- [x] Average of last X values (ex. after inputting 300 values the class will return the value, not the best solution, but a good start point)
- [x] Average from last X seconds (the class would have to measure 5 seconds with Timer and after 5 seconds it would return an average FPS count).

There will probably be some surprises along the way, so I suggest rethinking the task and, most importantly:
- [x] Implement the class together with tests.

**Comment by mkulagowski** [comment]
[Link to gerrit](https://review.gerrithub.io/#/c/257340) - class + tests and comments.
