### ISSUE TITLE
Final project documentation

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRft#16]
We will also need final documentation, when we return our project.

Requirements (from Mr. Biedrzycki's page):
- [x] Overall it should fulfill following sentence, roughly translated from Polish: "Final documentation should present the project from its best possible side, however a good look at met problems is very important as well and it means, that the team properly understood the task. So, on one hand "good PR", on the other a critical approach to the work done."
- [x] A sheet with task list and its real manhours, compared to the one delivered at the very beginning of the project
- [x] List of realized features
- [x] App architecture description (description of which modules cooperate with each other, description of main classes and their role in the system)
- [x] App should be buildable and launchable on clean system after following instructions put inside a README file.

**Comment by lookeypl** [comment]
Updated description with requirements from Mr. Biedrzycki's page about the project.

**Comment by lookeypl** [comment]
Was done and approved at a blasing max point score! closing.
