### ISSUE TITLE
Voxel Rendering

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRft#3]
Renderer part with following features:
- [x] Drawing whatever is provided to the renderer
- [x] Handling any OGL-specific resource generation (VBs, IBs, shaders, etc)

Terrain Generator with following features:
- [x] Terrain mesh generation from voxel cloud
- [x] Efficient memory management
- [x] MOAR MOAR (look at spreadsheet and rewrite here).

**Comment by lookeypl** [comment]
Renderer skeleton is done. The task will be kept here since there are more issues regarding Renderer. Moving to Application deadline milestone.

**Comment by lookeypl** [comment]
This can be closed now. Any further improvements to renderer will be in a separate tasks.
