### ISSUE TITLE
Game Manager implementation

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRft#4]
A main class which will handle everything in the game.

Features:
- Handling entire game loop (below are in preferred order of update):
  - Gathering player input
  - Determining which chunks should be drawn
  - Rendering request from Voxel Renderer
- Keeping all other managers:
  - Window Manager
  - Terrain Manager
  - Renderer
- ...

**Comment by lookeypl** [comment]
The skeleton for Game Manager was provided. It will evolve with new features being added to it. Closing.
