### ISSUE TITLE
Basic repo structure

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRft#6]
Basic things to do:
- [x] Main repository directory tree
- [x] Solution and project files
- [x] CMake files

Moreover, some TODOs to keep in mind:
- [x] UTF16-to-UTF8 and 8-to-16 code in Window.hpp (should be in a common source file)
- [x] OGL Context to create (depends whether it should be done in Renderer, or in Window - needs investigation)

**Comment by lookeypl** [comment]
Main repo tree and solution: https://review.gerrithub.io/#/c/251319/

**Comment by lookeypl** [comment]
All done. Closing.
