### ISSUE TITLE
Terrain Manager

### ISSUE THREAD

**Issue by mkulagowski** [mkulagowski/MineZPRft#7]
Terrain Manager is responsible for creating cloud of points via Perlin Noise Generator, storing them in vertexBuffer, maintaining its copy on HDD and forwarding vertexBuffer to the renderer.
It holds enum class with different cube types.
- [x] Pre-work (after this point Map will be generated, but it will be slow/laggy/not-optimized-at-all):
  - [x] Generating map chunk
  - [x] Storing map chunk in vertexBuffer
  - [x] Communication with Renderer
- [x] Advanced features (speed up work for map; after this point the project should run smoothly and have a lot of free GPU for advanced renderer features):
  - [x] Fast culling of invisible voxels
  - [x] Greedy Meshing (should convert voxels into small number of triangles. Should be fast - it will be called often).
  - [x] Multithreaded map generation (additional thread generating all chunks as needed)
  - [x] Proper map chunk updating (when its needed)
  - [x] Memory management improvements (keep some chunks in memory until they are not needed / player is too far away from them / there is not enough place for new chunks). 
- [x] Additional work, aka. bonuses:
  - [x] Save/Load map chunk functions

**Comment by lookeypl** [comment]
App skeleton finished. Moving the task to Application Deadline milestone.

**Comment by lookeypl** [comment]
Done.
