### ISSUE TITLE
Remove #pragma once directives

### ISSUE THREAD

**Issue by lookeypl** [mkulagowski/MineZPRft#8]
# pragma once directives are not ISO-conformant. Remove all and replace with classic #ifdef ... #endif directives.

Macros should reflect file location on repostiory for uniqueness. For example, when a header is in Renderer/Common.hpp directory, create a block:

``` cpp
/**
 * typical boilerplate
 */

#ifndef __RENDERER_COMMON_HPP__
#define __RENDERER_COMMON_HPP__

// contents of header

#endif // __RENDERER_COMMON_HPP__
```

**Comment by mkulagowski** [comment]
Uhh...hate whole this mess with these defines...but i guess we don't have much choice this time.
Please keep in mind, to check those in reviews from now on!

**Comment by mkulagowski** [comment]
Commit is in [review](https://review.gerrithub.io/#/c/253983/)

**Comment by lookeypl** [comment]
Well, unfortunately, we don't have a choice.

Commit looks OK. I will merge it and rebase on top of it with my changes.

**Comment by mkulagowski** [comment]
merged
